### ISSUE TITLE
CRAN breakages

### ISSUE THREAD

**Issue by rsbivand** [reginalexavier/OpenLand#4]
Your CRAN breakages (revdep tested as your package uses **raster** are still present with **dplyr** from github:

```
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
   14. base::tryCatch(...)
   15. base:::tryCatchList(expr, classes, parentenv, handlers)
   16. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
   17. value[[3L]](cond)
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 108 | SKIPPED: 0 | WARNINGS: 49 | FAILED: 5 ]
  1. Failure: Behavior of the contingencyTable (@test_contingencyTable.R#41) 
  2. Failure: Behavior of acc_changes (@test_generalfunctions.R#13) 
  3. Failure: Behavior of acc_changes (@test_generalfunctions.R#14) 
  4. Failure: Behavior of acc_changes (@test_generalfunctions.R#15) 
  5. Error: Behavior of summary_map (@test_generalfunctions.R#53) 
  
  Error: testthat unit tests failed
  Execution halted
```

**Comment by reginalexavier** [comment]
Fixed with this new CRAN release 569b8a0b0fea7f23bd82375d2ff26d0f5a148df9

**Comment by rsbivand** [comment]
Not resolved, with 1.0.1 I see:

```* checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  ── 3. Failure: Behavior of acc_changes (@test_generalfunctions.R#14)  ──────────
  `acc_changes(raster::stack(demo_raster))` produced warnings.
  
  ── 4. Failure: Behavior of acc_changes (@test_generalfunctions.R#15)  ──────────
  `acc_changes(raster::brick(demo_raster))` produced warnings.
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 108 | SKIPPED: 0 | WARNINGS: 15 | FAILED: 4 ]
  1. Failure: Behavior of the contingencyTable (@test_contingencyTable.R#41) 
  2. Failure: Behavior of acc_changes (@test_generalfunctions.R#13) 
  3. Failure: Behavior of acc_changes (@test_generalfunctions.R#14) 
  4. Failure: Behavior of acc_changes (@test_generalfunctions.R#15) 
  
  Error: testthat unit tests failed
  Execution halted
```
```
R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(testthat)
> library(OpenLand)
> 
> test_check("OpenLand")
── 1. Failure: Behavior of the contingencyTable (@test_contingencyTable.R#41)  ─
`contingencyTable(raster::brick(demo_raster), pixelresolution = 1)` produced warnings.

── 2. Failure: Behavior of acc_changes (@test_generalfunctions.R#13)  ──────────
`acc_changes(demo_raster)` produced warnings.

── 3. Failure: Behavior of acc_changes (@test_generalfunctions.R#14)  ──────────
`acc_changes(raster::stack(demo_raster))` produced warnings.

── 4. Failure: Behavior of acc_changes (@test_generalfunctions.R#15)  ──────────
`acc_changes(raster::brick(demo_raster))` produced warnings.

══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 108 | SKIPPED: 0 | WARNINGS: 15 | FAILED: 4 ]
1. Failure: Behavior of the contingencyTable (@test_contingencyTable.R#41) 
2. Failure: Behavior of acc_changes (@test_generalfunctions.R#13) 
3. Failure: Behavior of acc_changes (@test_generalfunctions.R#14) 
4. Failure: Behavior of acc_changes (@test_generalfunctions.R#15) 

Error: testthat unit tests failed
Execution halted
```

```
> acc_changes(demo_raster)
[[1]]
class      : RasterLayer 
dimensions : 100, 100, 10000  (nrow, ncol, ncell)
resolution : 1, 1  (x, y)
extent     : 0, 100, 0, 100  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=21 +south +ellps=GRS80 +units=m +no_defs 
source     : memory
names      : layer 
values     : 0, 5  (min, max)


[[2]]
# A tibble: 6 x 3
  PxValue    Qt Percent
    <int> <int>   <dbl>
1       0     2    0.02
2       1    66    0.66
3       2   522    5.22
4       3  1998   20.0 
5       4  4070   40.7 
6       5  3342   33.4 

Warning messages:
1: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on GRS80 ellipsoid in CRS definition
2: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on GRS80 ellipsoid in CRS definition
3: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on GRS80 ellipsoid in CRS definition
4: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on GRS80 ellipsoid in CRS definition
5: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on GRS80 ellipsoid in CRS definition
6: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on GRS80 ellipsoid in CRS definition
```
You should expect warnings with the development version of **rgdal**, `testthat::expect_silent()` is the source of your problems. Do not use it until you have fully adapted to new PROJ and GDAL.
